version: '3.8'

services:
  behat:
    build:
      context: ./docker/behat
      dockerfile: Dockerfile
    image: projeto-php-behat:latest
    volumes:
      - ./:/app:delegated
    working_dir: /app
    environment:
      - APP_ENV=testing
      - APP_URL=http://host.docker.internal:8000
    tty: true
    stdin_open: true
