global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "laravel"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["app:9000"]

rule_files:
  - "/etc/prometheus/rules/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
